#!url=https://raw.githubusercontent.com/quocchienn/YouTube_Spotify/refs/heads/module/Block_Ads_YouTbe.module
#!name=Block Ads YouTbe
#!desc=Quocchien

[Rule]
RULE-SET,https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/ruleset/reject.txt,REJECT-NO-DROP
RULE-SET,https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-surge-rule.conf,REJECT-NO-DROP
RULE-SET,https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-surge-rewrite.conf,REJECT-NO-DROP
RULE-SET,https://raw.githubusercontent.com/bigdargon/hostsVN/master/extensions/threat/surge-rule.conf,REJECT-NO-DROP
